baseURL = "https://fruity-fkf.github.io"
title = "FKF's blog"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "Hugo-Gruvbox-Theme"
[params.about]
title = "FKF's blog"
description = "FKF's silly little blog where it writes silly little articles and rants :3"
copyright = "nuh uh copyrights are kinda cringe"
pagination.pagerSize = 5
enableRobotsTXT = true
[params.author]
name = "FKF"
email = "fkf.6106@gmail.com"

[params]
    enableRelatedPosts = false
    relatedPostsNumber = 2
    #For Utterances Comments Feature - need to add repo
# #Main Menu (below header)
# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4


# [[menu.footer]]
# name = "PrivacyPolicy"
# url = "/privacypolicy"
# weight = 2
#
# Social Media Links (in header)
# Uses feather icons (search icon names on the site)
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/fruity-fkf"
#enable tags
# [taxonomies]
#   tag = "tags"

# # allow raw HTML
# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#       unsafe = true
#
# # Syntax Highlighting
# pygmentsUseClasses = true
# pygmentsCodefences = true
# [markup.highlight]
#     codeFences = true
#     guessSyntax = true
#     hl_Lines = ""
#     lineNoStart = 1
#     lineNos = true
#     lineNumbersInTable = true
#     tabWidth = 4
#     noClasses = false
#
# # Table of content depth and list type
# [markup.tableOfContents]
#   endLevel = 4
#   ordered = false
#   startLevel = 2
#
